[build]
builder = "NIXPACKS"

[deploy]
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[environments.production]
PORT = "8000"
HOST = "0.0.0.0"

[environments.production.variables]
PYTHONPATH = "/app"
PYTHONUNBUFFERED = "1"
